### ISSUE TITLE
No free volumes

### ISSUE THREAD

**Issue by cfirs** [atroo/node-weedfs#10]
I tried to start new server with the command: 
weed server -master.port=9333 -dir=data -volume.port=8080

and then to insert new file, but i get the following error:
No free volumes left!

**The error does not appear on each run**

**Comment by phal0r** [comment]
Did you have a look at the admin ui of seaweed? Did it show a working topology? One Volume Server should be visible and at least one volume.

**Comment by atroo** [comment]
Closed due to inactivity.
